import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import Footer from "@/components/Footer/footer";

const inter =({ subsets: ["latin"] });



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.classname}>
        <div className="container">

        <Navbar />
        {children}
        <Footer />
        </div>
      </body>
    </html>
  );
}
