name: Deploy Next.js to EC2

on:
  push:
    branches:
      - main # Trigger workflow when pushing to main branch


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install
          npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          # script: | -
          #   cd /home/ubuntu/my-app
          #   git pull origin main
          #   npm install
          #   npm run build
          #   pm2 restart my-app

